name: Earthquake Monitor Odd Minutes

on:
  schedule:
    - cron: "1-59/2 * * * *"  # 1,3,5,7... 分鐘
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main script
        run: python main.py
